/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lk.ijse.reservation.view;

import java.awt.Color;
import java.awt.Dimension;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JPanel;

/**
 *
 * @author Sachinda Nipun
 */
public class DashBoard extends javax.swing.JFrame {

    /**
     * Creates new form DashBoard
     */
    public DashBoard() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        ReportBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        RoomBtn = new javax.swing.JButton();
        GuestBtn = new javax.swing.JButton();
        ReservationBtn = new javax.swing.JButton();
        Fasilitybtn = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        Mealsbtn = new javax.swing.JButton();
        MainPanel = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new java.awt.CardLayout());

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ReportBtn.setBackground(new java.awt.Color(0, 0, 0));
        ReportBtn.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        ReportBtn.setForeground(new java.awt.Color(51, 255, 51));
        ReportBtn.setText("Report");
        ReportBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ReportBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ReportBtnMouseExited(evt);
            }
        });
        ReportBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReportBtnActionPerformed(evt);
            }
        });
        jPanel2.add(ReportBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 480, 180, 80));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/reservation/image/Iconic_2302(0)_64.png"))); // NOI18N
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 60, 70));

        RoomBtn.setBackground(new java.awt.Color(0, 0, 0));
        RoomBtn.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        RoomBtn.setForeground(new java.awt.Color(51, 255, 51));
        RoomBtn.setText("  ROOM");
        RoomBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                RoomBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                RoomBtnMouseExited(evt);
            }
        });
        RoomBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RoomBtnActionPerformed(evt);
            }
        });
        jPanel2.add(RoomBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 180, 70));

        GuestBtn.setBackground(new java.awt.Color(0, 0, 0));
        GuestBtn.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        GuestBtn.setForeground(new java.awt.Color(51, 255, 51));
        GuestBtn.setText("Guest");
        GuestBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                GuestBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                GuestBtnMouseExited(evt);
            }
        });
        GuestBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuestBtnActionPerformed(evt);
            }
        });
        jPanel2.add(GuestBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 180, 70));

        ReservationBtn.setBackground(new java.awt.Color(0, 0, 0));
        ReservationBtn.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        ReservationBtn.setForeground(new java.awt.Color(51, 255, 51));
        ReservationBtn.setText("   Reservation");
        ReservationBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ReservationBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ReservationBtnMouseExited(evt);
            }
        });
        ReservationBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReservationBtnActionPerformed(evt);
            }
        });
        jPanel2.add(ReservationBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 180, 70));

        Fasilitybtn.setBackground(new java.awt.Color(0, 0, 0));
        Fasilitybtn.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        Fasilitybtn.setForeground(new java.awt.Color(51, 255, 51));
        Fasilitybtn.setText("Facilities");
        Fasilitybtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                FasilitybtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                FasilitybtnMouseExited(evt);
            }
        });
        Fasilitybtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FasilitybtnActionPerformed(evt);
            }
        });
        jPanel2.add(Fasilitybtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 320, 180, 70));

        jButton2.setBackground(new java.awt.Color(0, 0, 0));
        jButton2.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(51, 255, 51));
        jButton2.setText("       DashBoard");
        jButton2.setBorder(null);
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton2MouseExited(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 180, 70));

        Mealsbtn.setBackground(new java.awt.Color(0, 0, 0));
        Mealsbtn.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        Mealsbtn.setForeground(new java.awt.Color(51, 255, 51));
        Mealsbtn.setText("Meals");
        Mealsbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                MealsbtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                MealsbtnMouseExited(evt);
            }
        });
        Mealsbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MealsbtnActionPerformed(evt);
            }
        });
        jPanel2.add(Mealsbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 400, 180, 70));

        MainPanel.setBackground(new java.awt.Color(255, 255, 255));
        MainPanel.setLayout(new java.awt.CardLayout());

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/reservation/image/Entypo_2699(0)_64.png"))); // NOI18N
        jLabel2.setText("LOG OUT");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 18, 126, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/reservation/image/Entypo_d83d(0)_64.png"))); // NOI18N
        jLabel3.setText("PROFILE");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(959, 19, 141, -1));

        jLabel5.setBackground(new java.awt.Color(0, 0, 0));
        jLabel5.setOpaque(true);
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 120, 80));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/reservation/image/spa 2.gif"))); // NOI18N
        jLabel4.setText("jLabel4");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 19, 385, 65));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(MainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 1340, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1297, 1297, 1297)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 8, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(MainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 631, Short.MAX_VALUE))
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseEntered
        jButton2.setBackground(Color.WHITE);
    }//GEN-LAST:event_jButton2MouseEntered

    private void jButton2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseExited
       jButton2.setBackground(Color.BLACK);
    }//GEN-LAST:event_jButton2MouseExited

    private void ReportBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ReportBtnMouseEntered
        ReportBtn.setBackground(Color.WHITE);
    }//GEN-LAST:event_ReportBtnMouseEntered

    private void ReportBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ReportBtnMouseExited
        ReportBtn.setBackground(Color.BLACK);
    }//GEN-LAST:event_ReportBtnMouseExited

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        MainPanel.removeAll();
        Dashboards dsh=new Dashboards();
        dsh.setVisible(true);
        MainPanel.add(dsh);
        dsh.setSize(MainPanel.getSize());
        MainPanel.repaint();
        MainPanel.revalidate();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void ReportBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReportBtnActionPerformed
         MainPanel.removeAll();
        RoomType rom=new RoomType();
        rom.setVisible(true);
        MainPanel.add(rom);
        rom.setSize(MainPanel.getSize());
        MainPanel.repaint();
        MainPanel.revalidate();
    }//GEN-LAST:event_ReportBtnActionPerformed

    private void RoomBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RoomBtnMouseEntered
        RoomBtn.setBackground(Color.WHITE);
    }//GEN-LAST:event_RoomBtnMouseEntered

    private void RoomBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RoomBtnMouseExited
        RoomBtn.setBackground(Color.BLACK);
    }//GEN-LAST:event_RoomBtnMouseExited

    private void RoomBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RoomBtnActionPerformed
       RoomMenu rom=new RoomMenu();
        MainPanel.removeAll();
        MainPanel.add(rom);
        rom.setVisible(true);
        rom.setSize(MainPanel.getSize());
        MainPanel.repaint();
        MainPanel.revalidate();
    }//GEN-LAST:event_RoomBtnActionPerformed

    private void GuestBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GuestBtnMouseEntered
        GuestBtn.setBackground(Color.WHITE);
    }//GEN-LAST:event_GuestBtnMouseEntered

    private void GuestBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GuestBtnMouseExited
       GuestBtn.setBackground(Color.BLACK);
    }//GEN-LAST:event_GuestBtnMouseExited

    private void GuestBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuestBtnActionPerformed
        
        try {
            Guests rom = new Guests();
            MainPanel.removeAll();
            rom.setVisible(true);
            rom.setSize(MainPanel.getSize());
            MainPanel.add(rom);
            MainPanel.repaint(); 
            MainPanel.revalidate();
        } catch (SQLException ex) {
            Logger.getLogger(DashBoard.class.getName()).log(Level.SEVERE, null, ex);
        }
        
       
       
                               
    }//GEN-LAST:event_GuestBtnActionPerformed

    private void ReservationBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ReservationBtnMouseEntered
        ReservationBtn.setBackground(Color.WHITE);
    }//GEN-LAST:event_ReservationBtnMouseEntered

    private void ReservationBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ReservationBtnMouseExited
        ReservationBtn.setBackground(Color.BLACK);
    }//GEN-LAST:event_ReservationBtnMouseExited

    private void ReservationBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReservationBtnActionPerformed
        MainPanel.removeAll();
        ManegeReservation rom=new ManegeReservation();
        rom.setVisible(true);
        MainPanel.add(rom);
        rom.setSize(MainPanel.getSize());
        MainPanel.repaint();
        MainPanel.revalidate();
    }//GEN-LAST:event_ReservationBtnActionPerformed

    private void FasilitybtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FasilitybtnMouseEntered
        Fasilitybtn.setBackground(Color.WHITE);
    }//GEN-LAST:event_FasilitybtnMouseEntered

    private void FasilitybtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FasilitybtnMouseExited
        Fasilitybtn.setBackground(Color.BLACK);
    }//GEN-LAST:event_FasilitybtnMouseExited

    private void FasilitybtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FasilitybtnActionPerformed
        MainPanel.removeAll();
        Fasilites fas=new Fasilites();
        fas.setVisible(true);
        MainPanel.add(fas);
        fas.setSize(MainPanel.getSize());
        MainPanel.repaint();
        MainPanel.revalidate();
    }//GEN-LAST:event_FasilitybtnActionPerformed

    private void MealsbtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MealsbtnMouseEntered
        Mealsbtn.setBackground(Color.WHITE);
    }//GEN-LAST:event_MealsbtnMouseEntered

    private void MealsbtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MealsbtnMouseExited
            Mealsbtn.setBackground(Color.BLACK);    }//GEN-LAST:event_MealsbtnMouseExited

    private void MealsbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MealsbtnActionPerformed
       MainPanel.removeAll();
        Meals mel=new Meals();
        mel.setVisible(true);
        MainPanel.add(mel);
        mel.setSize(MainPanel.getSize());
        MainPanel.repaint();
        MainPanel.revalidate();
    }//GEN-LAST:event_MealsbtnActionPerformed

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        this.dispose();
        Login log=new Login();
        log.setVisible(true);
    }//GEN-LAST:event_jLabel2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DashBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DashBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DashBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DashBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DashBoard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Fasilitybtn;
    private javax.swing.JButton GuestBtn;
    private static javax.swing.JPanel MainPanel;
    private javax.swing.JButton Mealsbtn;
    private javax.swing.JButton ReportBtn;
    private javax.swing.JButton ReservationBtn;
    private javax.swing.JButton RoomBtn;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables

public static JPanel getPanel(){
    return MainPanel;
}
}

