/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lk.ijse.reservation.view;

import java.awt.Color;
import java.math.BigDecimal;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;
import lk.ijde.Reservation.coman.IDGenarator;
import lk.ijse.reservation.controller.ManegeGuest;
import lk.ijse.reservation.core.dto.GuestDTO;

/**
 *
 * @author Sachinda Nipun
 */
public class Guests extends javax.swing.JPanel {

    /**
     * Creates new form Guests
     */
    public Guests() throws SQLException {
        initComponents();
        OrderID();
    
    loadAllGues();

        tblGuest.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent e) {

                if (tblGuest.getSelectedRow() == -1) {
                    return;
                }

                String customerId = tblGuest.getValueAt(tblGuest.getSelectedRow(), 0).toString();
                String customerFName = tblGuest.getValueAt(tblGuest.getSelectedRow(), 1).toString();
                String customerLName = tblGuest.getValueAt(tblGuest.getSelectedRow(), 2).toString();
                String customerGender = tblGuest.getValueAt(tblGuest.getSelectedRow(), 3).toString();
                String customeridtype = tblGuest.getValueAt(tblGuest.getSelectedRow(), 4).toString();
                String customerIdnumber = tblGuest.getValueAt(tblGuest.getSelectedRow(), 5).toString();
                String customerContact = tblGuest.getValueAt(tblGuest.getSelectedRow(), 6).toString();
                String customerEmail = tblGuest.getValueAt(tblGuest.getSelectedRow(), 7).toString();
                

                txtGuestId.setText(customerId);
                txtFname.setText(customerFName);
                txtLName.setText(customerContact);
                txtGenderl.setText(customerGender);
                ComboIDType.setSelectedItem(customeridtype);
                txtIdNumber.setText(customerIdnumber);
                txtContactNumber.setText(customerContact);
                txtEmail.setText(customerEmail);
            }
        });
    }
    
    
    private void loadAllGues() {
        try {
            tblGuest.setBackground(new Color(0xFFFFFF));
            ArrayList<GuestDTO> allGuest = ManegeGuest.getAllGuest();

            DefaultTableModel dtm = (DefaultTableModel) tblGuest.getModel();

            dtm.setRowCount(0);

            if (allGuest != null) {

                for (GuestDTO Guest : allGuest) {

                    Object[] rowData = {
                        Guest.getId(),
                        Guest.getFirstName(),
                        Guest.getLastName(),
                        Guest.getGender(),
                        Guest.getIDType(),
                        Guest.getIdNumber(),
                        Guest.getContactNo(),
                        Guest.getEMail()
                    };

                    dtm.addRow(rowData);

                }

            }

        } catch (Exception ex) {
            Logger.getLogger(ManegeGuest.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtGuestId = new javax.swing.JTextField();
        txtLName = new javax.swing.JTextField();
        txtGenderl = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        btnAdd = new javax.swing.JButton();
        Deletbtn = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblGuest = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtFname = new javax.swing.JTextField();
        txtIdNumber = new javax.swing.JTextField();
        txtContactNumber = new javax.swing.JTextField();
        ComboIDType = new javax.swing.JComboBox<>();
        jButton4 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        GuestIdtxt = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        GuestName = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 204, 204));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        add(txtGuestId, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 65, 210, 40));

        txtLName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLNameActionPerformed(evt);
            }
        });
        add(txtLName, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 180, 260, 40));
        add(txtGenderl, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 240, 140, 41));

        txtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailActionPerformed(evt);
            }
        });
        add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 480, 250, 40));

        jLabel7.setBackground(new java.awt.Color(0, 0, 204));
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/reservation/image/saasa.png"))); // NOI18N
        jLabel7.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 560, 40, 40));

        btnAdd.setBackground(new java.awt.Color(0, 0, 153));
        btnAdd.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        btnAdd.setForeground(new java.awt.Color(255, 255, 255));
        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        add(btnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 560, 120, 40));

        Deletbtn.setBackground(new java.awt.Color(0, 0, 204));
        Deletbtn.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        Deletbtn.setForeground(new java.awt.Color(255, 255, 255));
        Deletbtn.setText("Delet");
        Deletbtn.setBorderPainted(false);
        Deletbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeletbtnActionPerformed(evt);
            }
        });
        add(Deletbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 530, 82, 49));

        jButton3.setBackground(new java.awt.Color(0, 0, 153));
        jButton3.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("View");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 530, 80, 48));

        tblGuest.setBackground(new java.awt.Color(51, 51, 51));
        tblGuest.setFont(new java.awt.Font("Yu Gothic", 0, 10)); // NOI18N
        tblGuest.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "First name", "Last Name", "Gender", "ID Type", "Id number", "Contact", "Email"
            }
        ));
        tblGuest.setGridColor(new java.awt.Color(102, 255, 255));
        tblGuest.setOpaque(false);
        tblGuest.setRowHeight(35);
        jScrollPane1.setViewportView(tblGuest);
        if (tblGuest.getColumnModel().getColumnCount() > 0) {
            tblGuest.getColumnModel().getColumn(0).setPreferredWidth(70);
            tblGuest.getColumnModel().getColumn(1).setPreferredWidth(160);
            tblGuest.getColumnModel().getColumn(2).setPreferredWidth(160);
            tblGuest.getColumnModel().getColumn(4).setPreferredWidth(100);
            tblGuest.getColumnModel().getColumn(5).setPreferredWidth(150);
            tblGuest.getColumnModel().getColumn(6).setPreferredWidth(100);
            tblGuest.getColumnModel().getColumn(7).setPreferredWidth(150);
        }

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 50, 770, 460));

        jLabel10.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(153, 153, 153));
        jLabel10.setText("Gender");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 101, -1));

        jLabel5.setBackground(new java.awt.Color(51, 51, 51));
        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("  ADD Guest");
        jLabel5.setOpaque(true);
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 390, 30));

        txtFname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFnameActionPerformed(evt);
            }
        });
        add(txtFname, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 120, 260, 40));

        txtIdNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdNumberActionPerformed(evt);
            }
        });
        add(txtIdNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 360, 250, 40));

        txtContactNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtContactNumberActionPerformed(evt);
            }
        });
        add(txtContactNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 420, 250, 40));

        ComboIDType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Passport", "NIC", "Licence" }));
        add(ComboIDType, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 300, 270, 30));

        jButton4.setBackground(new java.awt.Color(0, 0, 153));
        jButton4.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Upadate");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 530, -1, 48));

        jLabel11.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(153, 153, 153));
        jLabel11.setText("Contact No.");
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 420, 90, 40));

        GuestIdtxt.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        GuestIdtxt.setForeground(new java.awt.Color(153, 153, 153));
        GuestIdtxt.setText("Guest ID");
        add(GuestIdtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 100, 36));

        jLabel9.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(153, 153, 153));
        jLabel9.setText("Id number");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, 101, -1));

        GuestName.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        GuestName.setForeground(new java.awt.Color(153, 153, 153));
        GuestName.setText("First Name");
        add(GuestName, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 77, 36));

        jLabel1.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 153, 153));
        jLabel1.setText("Last Name");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 101, -1));

        jLabel2.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 153, 153));
        jLabel2.setText("ID Type");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 64, 50));

        jLabel3.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 153, 153));
        jLabel3.setText("E-Mail");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 480, 90, 41));

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        jLabel4.setOpaque(true);
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 390, 610));

        jLabel8.setFont(new java.awt.Font("Lucida Bright", 1, 18)); // NOI18N
        jLabel8.setText("Guest Details");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 20, 210, 20));

        jLabel6.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(153, 153, 153));
        jLabel6.setText("Tel.number");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, 101, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void txtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        
        try {
            GuestDTO Guest = new GuestDTO(
                    txtGuestId.getText(),
                    txtFname.getText(),
                    txtLName.getText(),
                    txtGenderl.getText(),
                    ComboIDType.getSelectedItem().toString(),
                    txtIdNumber.getText(),
                    txtContactNumber.getText(),
                    txtEmail.getText()
            );
            boolean  result;
            result = ManegeGuest.addGuest(Guest);
            if (result) {
                JOptionPane.showMessageDialog(this, "Added sucessfully");
                OrderID();
                loadAllGues();
                // textFieldNull();
            } else {
                JOptionPane.showMessageDialog(this, "oops Added Fail", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } catch (Exception ex) {
            Logger.getLogger(Guests.class.getName()).log(Level.SEVERE, null, ex);
        }
            
           
          
            
    
    }//GEN-LAST:event_btnAddActionPerformed

    private void DeletbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeletbtnActionPerformed
       GuestDTO Guest = new GuestDTO(
               txtGuestId.getText(),
                    txtFname.getText(),
                    txtLName.getText(),
                    txtGenderl.getText(),
                    ComboIDType.getSelectedItem().toString(),
                    txtIdNumber.getText(),
                    txtContactNumber.getText(),
                    txtEmail.getText()
                );
        try {
            boolean result = ManegeGuest.deleteGuest(Guest);

            if (result) {
                JOptionPane.showMessageDialog(this, "Guest has been successfully deleted.");
                loadAllGues();
            } else {
                JOptionPane.showMessageDialog(this, "Guest hasn't been deleted due to some error");
            }

        } catch (SQLException ex) {
            String errorMsg;
                switch (ex.getErrorCode()) {
                    case 1062:
                        errorMsg = "Duplicate entry has been found. Please enter valid Supplier Id to proceed.";
                        break;
                    default:
                        errorMsg = "Guest has been failed to add";
                        break;
                }
                JOptionPane.showMessageDialog(this, errorMsg, "Error", JOptionPane.ERROR_MESSAGE);
        } catch (Exception ex) {
            Logger.getLogger(Guests.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_DeletbtnActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
         
         
        try {
            GuestDTO Guest = new GuestDTO(
               txtGuestId.getText(),
                    txtFname.getText(),
                    txtLName.getText(),
                    txtGenderl.getText(),
                    ComboIDType.getSelectedItem().toString(),
                    txtIdNumber.getText(),
                    txtContactNumber.getText(),
                    txtEmail.getText()
                );
            
            
                boolean result;
                result = ManegeGuest.updateGuest(Guest);
            

            if (result) {
                JOptionPane.showMessageDialog(this, "Guest has been successfully upddateed.");
                OrderID();
                loadAllGues();
            } else {
                JOptionPane.showMessageDialog(this, "Customer hasn't been upddated due to some error");
            }

        } catch (Exception ex) {
            Logger.getLogger(Guests.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void txtLNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLNameActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void txtFnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFnameActionPerformed

    private void txtIdNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdNumberActionPerformed

    private void txtContactNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtContactNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtContactNumberActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ComboIDType;
    private javax.swing.JButton Deletbtn;
    private javax.swing.JLabel GuestIdtxt;
    private javax.swing.JLabel GuestName;
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblGuest;
    private javax.swing.JTextField txtContactNumber;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtFname;
    private javax.swing.JTextField txtGenderl;
    private javax.swing.JTextField txtGuestId;
    private javax.swing.JTextField txtIdNumber;
    private javax.swing.JTextField txtLName;
    // End of variables declaration//GEN-END:variables

private void OrderID()  {
        
        try {
            String orderId=null;
            try {
                orderId = IDGenarator.getNewID("Guest ", "GID ", "C");
            } catch (SQLException ex) {
                Logger.getLogger(Guests.class.getName()).log(Level.SEVERE, null, ex);
            }
            txtGuestId.setText(orderId);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Guests.class.getName()).log(Level.SEVERE, null, ex);
        }
}
}

        
