/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lk.ijse.reservation.view;

import java.awt.Color;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import lk.ijse.reservation.controller.ManegeFasilites;
import lk.ijse.reservation.controller.ManegeRoomType;
import lk.ijse.reservation.core.dto.FasilitesDTO;
import lk.ijse.reservation.core.dto.RoomTypeDTO;

/**
 *
 * @author Sachinda Nipun
 */
public class RoomType extends javax.swing.JPanel {

    /**
     * Creates new form RoomType
     */
    public RoomType() {
        initComponents();
        loadAllCustomerIds();
       // loadAllFasilites();
    }

      private void loadAllCustomerIds(){
        
        try {
            ArrayList<FasilitesDTO> allFasilites = ManegeFasilites.getAllFalitites();

            FasilitessIDcombo.removeAllItems();
            if (allFasilites == null) return;
            
            for (FasilitesDTO Fasilites : allFasilites) {
                FasilitessIDcombo.addItem(Fasilites.getName());
                
                
               //FasilitesNametxt.add(Fasilites.getName());
            }
        } catch (Exception ex) {
            Logger.getLogger(RoomType.class.getName()).log(Level.SEVERE, null, ex);
        }
      }

       
   
        
      
      

            
        
        


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        RoomTypeIdtxt = new org.jdesktop.swingx.JXTextField();
        jLabel12 = new javax.swing.JLabel();
        RoomTyprtxt = new org.jdesktop.swingx.JXTextField();
        bedTypetxt = new org.jdesktop.swingx.JXTextField();
        jLabel1 = new javax.swing.JLabel();
        RoomTyprDescriptiontxt = new org.jdesktop.swingx.JXTextField();
        jLabel5 = new javax.swing.JLabel();
        FasilitessIDcombo = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        Deletbtn = new javax.swing.JButton();
        Upadtebtn = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        TblRoomType = new org.jdesktop.swingx.JXTable();
        jLabel7 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new Color(0,0,0,0f));
        jPanel1.setOpaque(false);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setBackground(new java.awt.Color(0, 0, 153));
        jLabel2.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        jLabel2.setText("Room Type Description");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 180, 28));

        jLabel11.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        jLabel11.setText("Room Type ID");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 120, 30));
        jPanel1.add(RoomTypeIdtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 30, 170, 40));

        jLabel12.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        jLabel12.setText("Room Type");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 100, 30));
        jPanel1.add(RoomTyprtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 90, 310, 40));
        jPanel1.add(bedTypetxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 220, 280, 40));

        jLabel1.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        jLabel1.setText("Bed Type");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 120, 20));

        RoomTyprDescriptiontxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RoomTyprDescriptiontxtActionPerformed(evt);
            }
        });
        jPanel1.add(RoomTyprDescriptiontxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 150, 440, 47));

        jLabel5.setFont(new java.awt.Font("Lucida Bright", 1, 12)); // NOI18N
        jLabel5.setText("Fasilites Name");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, 108, 38));

        jPanel1.add(FasilitessIDcombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 280, 141, 39));

        jButton1.setBackground(new java.awt.Color(0, 0, 153));
        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Make");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 280, 90, 50));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 729, 343));

        Deletbtn.setBackground(new java.awt.Color(0, 0, 153));
        Deletbtn.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        Deletbtn.setForeground(new java.awt.Color(255, 255, 255));
        Deletbtn.setText("Delet");
        Deletbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeletbtnActionPerformed(evt);
            }
        });
        add(Deletbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 410, 120, 50));

        Upadtebtn.setBackground(new java.awt.Color(0, 0, 153));
        Upadtebtn.setForeground(new java.awt.Color(255, 255, 255));
        Upadtebtn.setText("Update");
        Upadtebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpadtebtnActionPerformed(evt);
            }
        });
        add(Upadtebtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 480, 120, 50));

        jButton4.setBackground(new java.awt.Color(0, 0, 153));
        jButton4.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("View");
        add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 550, 120, 50));

        TblRoomType.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Type", "Description", "Bes Type", "Fasilites"
            }
        ));
        jScrollPane2.setViewportView(TblRoomType);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(91, 397, 648, 258));

        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 20, 100, 40));

        jLabel3.setBackground(new java.awt.Color(153, 153, 153));
        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("    Fasilites Details");
        jLabel3.setOpaque(true);
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 350, 1200, 30));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/reservation/image/Entypo_e4ad(0)_64.png"))); // NOI18N
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 10, 80, 50));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("BACK");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 10, 60, 50));
    }// </editor-fold>//GEN-END:initComponents

    private void RoomTyprDescriptiontxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RoomTyprDescriptiontxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RoomTyprDescriptiontxtActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            RoomTypeDTO Room;
            Room = new RoomTypeDTO(
                    RoomTypeIdtxt.getText(),
                    RoomTyprtxt.getText(),
                    RoomTyprDescriptiontxt.getText(),
                    bedTypetxt.getText(),
                    FasilitessIDcombo.getSelectedItem().toString()
            );
            
            boolean result = ManegeRoomType.addRoom(Room);

            if (result) {
                JOptionPane.showMessageDialog(this, "Customer has been successfully added.");
                  loadAllRooms();
            } else {
                JOptionPane.showMessageDialog(this, "Customer hasn't been added due to some error");
            }
        } catch (Exception ex) {
            Logger.getLogger(RoomType.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
        private void loadAllRooms(){
        
        try {
            ArrayList<RoomTypeDTO> allItems = ManegeRoomType.getAllRoomsTypes();
            
            DefaultTableModel dtm = (DefaultTableModel) TblRoomType.getModel();
            
            dtm.setRowCount(0);
            
            if (allItems != null){
                
                for (RoomTypeDTO RoomType : allItems) {
                    
                    Object[] rowData = {
                        RoomType.getId(),
                        RoomType.getType(),
                        RoomType.getDetails(),
                        RoomType.getBedType(),
                        RoomType.getFasilites()
                    };
                    
                    dtm.addRow(rowData);
                    
                }
            }
        } catch (Exception ex) {
            Logger.getLogger(RoomType.class.getName()).log(Level.SEVERE, null, ex);
        }
      
    
    }//GEN-LAST:event_jButton1ActionPerformed

    private void DeletbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeletbtnActionPerformed
        try {
            RoomTypeDTO item = new RoomTypeDTO(RoomTypeIdtxt.getText(),
                    RoomTyprtxt.getText(),
                    RoomTyprDescriptiontxt.getText(),
                    bedTypetxt.getText(),
                    FasilitessIDcombo.getSelectedItem().toString());
            
            
            boolean result = ManegeRoomType.deleteRoom(item);
            
            if (result){
                JOptionPane.showMessageDialog(this, "Item has been successfully deleted.");
                loadAllRooms();                
            }else{
                JOptionPane.showMessageDialog(this, "Item hasn't been deleted due to some error");
            }
        } catch (Exception ex) {
            Logger.getLogger(RoomType.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_DeletbtnActionPerformed

    private void UpadtebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpadtebtnActionPerformed
        try {
            RoomTypeDTO Room = new RoomTypeDTO(RoomTypeIdtxt.getText(),
                    RoomTyprtxt.getText(),
                    RoomTyprDescriptiontxt.getText(),
                    bedTypetxt.getText(),
                    FasilitessIDcombo.getSelectedItem().toString());
            
            
            boolean result = ManegeRoomType.updateRoom(Room);
            
            if (result){
                JOptionPane.showMessageDialog(this, "Item has been successfully deleted.");
                loadAllRooms();                
            }else{
                JOptionPane.showMessageDialog(this, "Item hasn't been deleted due to some error");
            }
        } catch (Exception ex) {
            Logger.getLogger(RoomType.class.getName()).log(Level.SEVERE, null, ex);
        }
       
    }//GEN-LAST:event_UpadtebtnActionPerformed

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        JPanel pnl=DashBoard.getPanel();
       pnl.removeAll();
        RoomMenu dsh=new RoomMenu();
        dsh.setVisible(true);
        pnl.add(dsh);
        dsh.setSize(pnl.getSize());
        pnl.repaint();
        pnl.revalidate();
    }//GEN-LAST:event_jLabel7MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Deletbtn;
    private javax.swing.JComboBox<String> FasilitessIDcombo;
    private org.jdesktop.swingx.JXTextField RoomTypeIdtxt;
    private org.jdesktop.swingx.JXTextField RoomTyprDescriptiontxt;
    private org.jdesktop.swingx.JXTextField RoomTyprtxt;
    private org.jdesktop.swingx.JXTable TblRoomType;
    private javax.swing.JButton Upadtebtn;
    private org.jdesktop.swingx.JXTextField bedTypetxt;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
