/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lk.ijse.reservation.view;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;
import lk.ijse.reservation.controller.ManegeGuest;
import lk.ijse.reservation.controller.ManegeRoom;
import lk.ijse.reservation.controller.ManegeRoomType;
import lk.ijse.reservation.core.dto.GuestDTO;
import lk.ijse.reservation.core.dto.RoomTypeDTO;
import lk.ijse.reservation.core.dto.RoomsDTO;

/**
 *
 * @author Sachinda Nipun
 */
public class Room extends javax.swing.JPanel {

    /**
     * Creates new form NewJPanel
     */
    public Room() {
        initComponents();
        loadAllCustomerIds();
        loadAllRoomTypes();
        loadAllRooms();

         tblRoom.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent e) {

                if (tblRoom.getSelectedRow() == -1) {
                    return;
                }

                String RoomTYpeId = tblRoom.getValueAt(tblRoom.getSelectedRow(), 0).toString();
                String RoomType = tblRoom.getValueAt(tblRoom.getSelectedRow(), 1).toString();
                String RoomId = tblRoom.getValueAt(tblRoom.getSelectedRow(), 2).toString();
                String RoomNumber = tblRoom.getValueAt(tblRoom.getSelectedRow(), 3).toString();
                String RoomFlow = tblRoom.getValueAt(tblRoom.getSelectedRow(), 4).toString();
                String RoomPrice = tblRoom.getValueAt(tblRoom.getSelectedRow(), 5).toString();

                
                

                RoomTypeID.setSelectedItem(RoomTYpeId);
                RoomTypecombo.setSelectedItem(RoomType);
                RoomIdText.setText(RoomId);
                RoomNumberTxt.setText(RoomNumber);
                RoomFlowTxt.setText(RoomFlow);
                RoomPricetxt.setText(RoomPrice);
                
            }
        });
    }
     private void loadAllCustomerIds(){
        
        try {
            ArrayList<RoomTypeDTO> allCustomers = ManegeRoomType.getAllRoomsTypes();

            RoomTypeID.removeAllItems();
            if (allCustomers == null) return;
            
            for (RoomTypeDTO customer : allCustomers) {
                RoomTypeID.addItem(customer.getId());
            }
        } catch (Exception ex) {
            Logger.getLogger(Room.class.getName()).log(Level.SEVERE, null, ex);
        }
        
     }
        private void loadAllRoomTypes(){
        
        try {
            ArrayList<RoomTypeDTO> allRoomStype = ManegeRoomType.getAllRoomsTypes();

            RoomTypecombo.removeAllItems();
            if (allRoomStype == null) return;
            
            for (RoomTypeDTO customer : allRoomStype) {
                RoomTypecombo.addItem(customer.getType());
            }
        } catch (Exception ex) {
            Logger.getLogger(Room.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    
    } private void loadAllRooms() {
        try {
            ArrayList<RoomsDTO> allRooms = ManegeRoom.getAllRooms();

            DefaultTableModel dtm = (DefaultTableModel) tblRoom.getModel();

            dtm.setRowCount(0);

            if (allRooms != null) {

                for (RoomsDTO Rooms : allRooms) {

                    Object[] rowData = {
                        Rooms.getRTID(),
                        Rooms.getRoomType(),
                        Rooms.getID(),
                        Rooms.getNumber(),
                        Rooms.getFlow(),
                        Rooms.getPrice()
                    };

                    dtm.addRow(rowData);

                }

            }

        } catch (Exception ex) {
            Logger.getLogger(ManegeGuest.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        RoomIdText = new javax.swing.JTextField();
        RoomNumberTxt = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        RoomFlowTxt = new org.jdesktop.swingx.JXTextField();
        jLabel9 = new javax.swing.JLabel();
        RoomPricetxt = new org.jdesktop.swingx.JXTextField();
        jLabel7 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        DeletButton = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        RoomTypecombo = new org.jdesktop.swingx.JXComboBox();
        RoomTypeID = new org.jdesktop.swingx.JXComboBox();
        jLabel4 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblRoom = new org.jdesktop.swingx.JXTable();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setText("Room ID");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(68, 132, 158, 49));
        jPanel1.add(RoomIdText, new org.netbeans.lib.awtextra.AbsoluteConstraints(232, 140, 138, 36));
        jPanel1.add(RoomNumberTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(232, 201, 138, 31));

        jLabel6.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 51, 51));
        jLabel6.setText("Flow");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(68, 259, 68, 23));

        jLabel3.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setText("Room Number");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(68, 199, 130, 31));

        jLabel1.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setText("Room Type ID");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 40, 120, 30));
        jPanel1.add(RoomFlowTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(232, 251, 143, 43));

        jLabel9.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(51, 51, 51));
        jLabel9.setText("Price");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(68, 321, 56, 29));

        RoomPricetxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RoomPricetxtActionPerformed(evt);
            }
        });
        jPanel1.add(RoomPricetxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(291, 312, 224, 50));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("RS.");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(232, 305, 55, 58));

        jButton1.setBackground(new java.awt.Color(0, 0, 153));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("ADD");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 410, 100, 46));

        DeletButton.setBackground(new java.awt.Color(0, 0, 153));
        DeletButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        DeletButton.setForeground(new java.awt.Color(255, 255, 255));
        DeletButton.setText("Delet");
        DeletButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeletButtonActionPerformed(evt);
            }
        });
        jPanel1.add(DeletButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 410, 98, 46));

        jButton3.setBackground(new java.awt.Color(0, 0, 153));
        jButton3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Update");
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 410, -1, 47));

        jButton4.setBackground(new java.awt.Color(0, 0, 153));
        jButton4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("View");
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 410, 83, 45));

        jLabel15.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(51, 51, 51));
        jLabel15.setText("Room Type");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, 104, 30));

        RoomTypecombo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel1.add(RoomTypecombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(232, 91, 240, 30));

        RoomTypeID.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        RoomTypeID.setForeground(new java.awt.Color(255, 255, 255));
        RoomTypeID.setFont(new java.awt.Font("Lucida Bright", 1, 12)); // NOI18N
        RoomTypeID.setOpaque(false);
        jPanel1.add(RoomTypeID, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 30, 198, 40));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 57, -1, 467));

        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 20, 100, 36));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/reservation/image/Entypo_e4ad(0)_64.png"))); // NOI18N
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 10, 80, 50));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel11.setText("BACK");
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 10, 60, 50));

        tblRoom.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Room Type ID", "Room Type", "Room ID", "Room Number", "Room Flow", "Price"
            }
        ));
        jScrollPane1.setViewportView(tblRoom);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 90, 741, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void RoomPricetxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RoomPricetxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RoomPricetxtActionPerformed

    private void DeletButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeletButtonActionPerformed
         try {
            RoomsDTO Room;
            Room = new RoomsDTO(
                    RoomTypeID.getSelectedItem().toString(),
                    RoomTypecombo.getSelectedItem().toString(),
                    RoomIdText.getText(),
                    RoomNumberTxt.getText(),
                    RoomFlowTxt.getText(),
                    new BigDecimal(RoomPricetxt.getText())
                    
            );
            
            boolean result = ManegeRoom.deleteRoom(Room);

            if (result) {
                JOptionPane.showMessageDialog(this, "Room has been successfully added.");
                  loadAllRooms();
            } else {
                JOptionPane.showMessageDialog(this, "Room hasn't been added due to some error");
            }
        } catch (Exception ex) {
            Logger.getLogger(RoomType.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_DeletButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
         try {
            RoomsDTO Room;
            Room = new RoomsDTO(
                    RoomTypeID.getSelectedItem().toString(),
                    RoomTypecombo.getSelectedItem().toString(),
                    RoomIdText.getText(),
                    RoomNumberTxt.getText(),
                    RoomFlowTxt.getText(),
                    new BigDecimal(RoomPricetxt.getText())
                    
            );
            
            boolean result = ManegeRoom.addRoom(Room);

            if (result) {
                JOptionPane.showMessageDialog(this, "Room has been successfully added.");
                 loadAllRooms();
            } else {
                JOptionPane.showMessageDialog(this, "Room hasn't been added due to some error");
            }
        } catch (Exception ex) {
            Logger.getLogger(RoomType.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
       JPanel pnl=DashBoard.getPanel();
       pnl.removeAll();
        RoomMenu dsh=new RoomMenu();
        dsh.setVisible(true);
        pnl.add(dsh);
        dsh.setSize(pnl.getSize());
        pnl.repaint();
        pnl.revalidate();
    }//GEN-LAST:event_jLabel4MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton DeletButton;
    private org.jdesktop.swingx.JXTextField RoomFlowTxt;
    private javax.swing.JTextField RoomIdText;
    private javax.swing.JTextField RoomNumberTxt;
    private org.jdesktop.swingx.JXTextField RoomPricetxt;
    private org.jdesktop.swingx.JXComboBox RoomTypeID;
    private org.jdesktop.swingx.JXComboBox RoomTypecombo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private org.jdesktop.swingx.JXTable tblRoom;
    // End of variables declaration//GEN-END:variables
}
